// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ilzegemxlyocwqeohjwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsemVnZW14bHlvY3dxZW9oandoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NTM2NjgsImV4cCI6MjA4MDQyOTY2OH0.y-saxCkOYrlG9Y6F37khTMB0Vo08hr3Ce6bSa1v3xKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);